Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -1,6 +1,8 @@
 name: Python application
 
-on: [push]
+on:
+  push:
+  workflow_dispatch:
 
 permissions:
   contents: write
@@ -10,44 +12,44 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Setup Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: '3.x'
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.x'
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install pymysql pandas matplotlib sqlalchemy python-dotenv
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pymysql pandas matplotlib sqlalchemy python-dotenv
 
-    - name: Run consulta_mysql.py
-      run: python consulta_mysql.py || echo "consulta_mysql.py falló"
+      - name: Run consulta_mysql.py
+        run: python consulta_mysql.py || echo "consulta_mysql.py falló"
 
-    - name: Run generar_grafica.py
-      run: python generar_grafica.py || echo "generar_grafica.py falló"
+      - name: Run generar_grafica.py
+        run: python generar_grafica.py || echo "generar_grafica.py falló"
 
-    - name: Check if grafica.png exists
-      run: |
-        if [ ! -f grafica.png ]; then
-          echo "Error: El archivo grafica.png no se generó."
-          exit 1
-        fi
+      - name: Check if grafica.png exists
+        run: |
+          if [ ! -f grafica.png ]; then
+            echo "Error: El archivo grafica.png no se generó."
+            exit 1
+          fi
 
-    - name: Upload graph
-      uses: actions/upload-artifact@v4
-      with:
-        name: grafica
-        path: grafica.png
+      - name: Upload graph
+        uses: actions/upload-artifact@v4
+        with:
+          name: grafica
+          path: grafica.png
 
-    - name: Commit and push changes
-      run: |
-        git config --global user.name 'github-actions'
-        git config --global user.email 'github-actions@github.com'
-        git add .
-        git diff --quiet || git commit -m "Update generated graph"
-        git push
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Commit and push changes
+        run: |
+          git config --global user.name 'github-actions'
+          git config --global user.email 'github-actions@github.com'
+          git add .
+          git diff --quiet || git commit -m "Update generated graph"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
